### ISSUE TITLE
Does not build as described

### ISSUE THREAD

**Issue by shack** [cincheo/jsweet-quickstart#10] opened 2021-04-08 12:04 UTC
I tried the instruction from [the website](https://github.com/cincheo/jsweet-quickstart) and got

```
[ERROR] Failed to execute goal org.jsweet:jsweet-maven-plugin:3.0.0:jsweet (generate-js) on project jsweet-quickstart: Execution generate-js of goal org.jsweet:jsweet-maven-plugin:3.0.0:jsweet failed: Plugin org.jsweet:jsweet-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.jsweet:jsweet-maven-plugin:jar:3.0.0 -> org.jsweet:jsweet-transpiler:jar:3.0.0: Failed to read artifact descriptor for org.jsweet:jsweet-transpiler:jar:3.0.0: Could not transfer artifact org.jsweet:jsweet-transpiler:pom:3.0.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [jsweet-plugins-release (http://repository.jsweet.org/artifactory/plugins-release-local, default, releases+snapshots), jsweet-plugins-snapshots (http://repository.jsweet.org/artifactory/plugins-snapshot-local, default, releases+snapshots), jsweet-release (http://repository.jsweet.org/artifactory/libs-release-local, default, releases+snapshots), jsweet-snapshot (http://repository.jsweet.org/artifactory/libs-snapshot-local, default, releases+snapshots), jsweet-external (http://repository.jsweet.org/artifactory/ext-release-local, default, releases+snapshots)] -> [Help 1]
```

I work under Big Sur with an up to date homebrew with Maven 3.8.1 and OpenJDK 15.0.2. I also removed the `.m2` directory before to make sure that there are no old and conflicting maven settings.

**Comment by lgrignon** [comment] 2021-04-08 13:37
Duplicate of https://github.com/lgrignon/jsweet-maven-plugin/issues/60

**Closed as completed by lgrignon** 2021-04-08 13:37 UTC
